name = "SkyCraft1.5"
author = "Sky Splash"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24b7250bb443844fff77c11ca7a8ebc806ff2d653c66b9ce3a8c1f32487245af"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
