name = "SkyCraft1.5"
author = "Sky Splash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4ecd88e947c5396eb575d55838bd255630bf9d058597657d7c9ab7d17dbfe1c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
