name = "SkyCraft1.5"
author = "Sky Splash"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa51aaf5f4168e8f3c2603a50bce7c499ace1d29280481c3bac149e3bb237a3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
